# Generated by Django 3.2.5 on 2021-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название канала')),
                ('active', models.CharField(choices=[(0, 'Нет'), (1, 'Да')], default=0, max_length=2, verbose_name='Использование канала')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя типа канала доставки')),
                ('channel', models.CharField(max_length=32, unique=True, verbose_name='Канал')),
                ('connection_model', models.CharField(max_length=128, verbose_name='Как подключаться к каналу')),
            ],
            options={
                'verbose_name': 'Тип канала',
                'verbose_name_plural': 'Типы каналов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок отправляемого сообщения')),
                ('body', models.CharField(max_length=256, verbose_name='Содержимое сообщения')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания сообщения')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('published', models.CharField(choices=[(0, 'Нет'), (1, 'Да')], default=0, max_length=2, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_date', 'publish_date'],
            },
        ),
    ]
