
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    env_file:
      - .env
    ports:
      - 1337:8000
    depends_on:
      - rediska

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core flower  -l INFO --port=5566
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 5566:5566
    depends_on:
      - app
      - celery_beat
      - celery_worker

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker -l INFO --pool=solo -E
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - app
      - rediska

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core beat -l INFO -S django
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - app
      - rediska

  rediska:
    image: redis:6.2.4-alpine
