---
feeds:
  - title: '@habr'
    url: 'https://habr.com/ru/rss/all/all/?fl=en%2Cru&limit=100'
  - title: '@teletype'
    url: 'https://teletype.in/rss/jtprogru'
  - title: '@pythonscripts'
    url: 'https://python-scripts.com/feed'
  - title: '@boomburum'
    url: 'http://boomburum.ru/feed/'
  - title: '@lgiordani'
    url: 'http://lgiordani.com/atom.xml'
  - title: '@mattsegal'
    url: 'https://mattsegal.dev/feeds/all.atom.xml'
  - title: '@shwanoff'
    url: 'https://shwanoff.ru/feed/'
  - title: '@sitehome'
    url: 'https://blog.site-home.ru/rss.xml'
  - title: '@jtprog'
    url: 'https://jtprog.ru/index.xml'
  - title: '@devconnected'
    url: 'https://devconnected.com/feed/atom/'
  - title: '@popstas'
    url: 'http://feeds.feedburner.com/popstas'
  - title: '@shellhacks'
    url: 'https://www.shellhacks.com/ru/feed'
  - title: '@vas3k'
    url: 'https://vas3k.ru/rss/'
  - title: '@threadreaderapp'
    url: 'https://threadreaderapp.com/myrss/9ef236b6-aaee-44a9-9bbf-31d1b84c1622.rss'

