# Generated by Django 3.2.5 on 2021-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True, verbose_name='Название задания')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на раздел')),
                ('status', models.IntegerField(choices=[(1, 'Новое'), (2, 'Запущено'), (3, 'Готово')], default=1, verbose_name='Статус задания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.AlterModelOptions(
            name='rssitem',
            options={'verbose_name': 'RSS-запись', 'verbose_name_plural': 'RSS-записи'},
        ),
    ]
