# Generated by Django 3.2.5 on 2021-07-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_auto_20210714_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True, verbose_name='Название источника')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на источник')),
                ('status', models.IntegerField(choices=[(1, 'Новое'), (2, 'Запущено'), (3, 'Готово')], default=1, verbose_name='Статус обработки')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
