# Generated by Django 3.2.5 on 2021-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0004_rssitem_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssitem',
            options={'ordering': ['pub_date'], 'verbose_name': 'RSS-запись', 'verbose_name_plural': 'RSS-записи'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['title', 'status'], 'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='link',
            field=models.URLField(max_length=512, unique=True, verbose_name='Ссылка на статью'),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='posted',
            field=models.CharField(choices=[(0, 'Нет'), (1, 'Да')], default=0, max_length=2, verbose_name='Отправлено в TG'),
        ),
    ]
