# Generated by Django 3.2.5 on 2021-07-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0003_auto_20210714_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='posted',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0, verbose_name='Отправлено в TG'),
        ),
    ]
