MESSAGE_PUBLISHED_YES = 1
MESSAGE_PUBLISHED_NO = 0
MESSAGE_PUBLISHED_STATUS = (
    (MESSAGE_PUBLISHED_NO, 'Нет'),
    (MESSAGE_PUBLISHED_YES, 'Да'),
)


CHANNEL_ACTIVE_YES = 1
CHANNEL_ACTIVE_NO = 0
CHANNEL_ACTIVE_STATUS = (
    (CHANNEL_ACTIVE_NO, 'Нет'),
    (CHANNEL_ACTIVE_YES, 'Да')
)
